@echo off
setlocal EnableDelayedExpansion

:: ============================================================
:: install.bat — Source-mode installer for Costco Order Lookup
:: Requires Python 3.9+ on PATH. Run once to set up.
:: ============================================================

set "SCRIPT_DIR=%~dp0"
set "VENV_DIR=%SCRIPT_DIR%venv"
set "LAUNCHER=%SCRIPT_DIR%costco-lookup.bat"

echo.
echo === Costco Order Lookup - Windows Installer ===
echo.

:: ----------------------------------------------------------------
:: Step 1: Verify Python is available
:: ----------------------------------------------------------------
where python >nul 2>&1
if errorlevel 1 (
    echo [error] Python not found on PATH.
    echo         Download Python 3.9+ from https://www.python.org/downloads/
    echo         Check "Add Python to PATH" during installation.
    pause & exit /b 1
)

for /f "tokens=2 delims= " %%V in ('python --version 2^>^&1') do set "PY_VERSION=%%V"
for /f "tokens=1,2 delims=." %%A in ("!PY_VERSION!") do (
    set "PY_MAJOR=%%A"
    set "PY_MINOR=%%B"
)

if !PY_MAJOR! LSS 3 (
    echo [error] Python !PY_VERSION! is too old. Python 3.9+ is required.
    pause & exit /b 1
)
if !PY_MAJOR! EQU 3 if !PY_MINOR! LSS 9 (
    echo [error] Python !PY_VERSION! is too old. Python 3.9+ is required.
    pause & exit /b 1
)

echo [ok] Python !PY_VERSION! found.

:: ----------------------------------------------------------------
:: Step 2: Create virtual environment
:: ----------------------------------------------------------------
if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [ok] Virtual environment already exists.
) else (
    echo [....] Creating virtual environment...
    python -m venv "%VENV_DIR%"
    if errorlevel 1 (
        echo [error] Failed to create virtual environment.
        pause & exit /b 1
    )
    echo [ok] Virtual environment created.
)

:: ----------------------------------------------------------------
:: Step 3: Install dependencies
:: ----------------------------------------------------------------
echo [....] Installing dependencies...
"%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip --quiet
"%VENV_DIR%\Scripts\pip.exe" install -r "%SCRIPT_DIR%requirements.txt" --quiet
if errorlevel 1 (
    echo [error] pip install failed. Check your network connection.
    pause & exit /b 1
)
echo [ok] Dependencies installed.

:: ----------------------------------------------------------------
:: Step 4: Write costco-lookup.bat launcher
:: ----------------------------------------------------------------
echo [....] Creating launcher...
(
    echo @echo off
    echo :: Auto-generated by install.bat
    echo "%VENV_DIR%\Scripts\python.exe" "%SCRIPT_DIR%main.py" %%*
) > "%LAUNCHER%"
if errorlevel 1 (
    echo [error] Could not write %LAUNCHER%
    pause & exit /b 1
)
echo [ok] Launcher created: %LAUNCHER%

:: ----------------------------------------------------------------
:: Done
:: ----------------------------------------------------------------
echo.
echo === Installation complete! ===
echo.
echo   First-time setup:
echo     costco-lookup.bat --setup
echo.
echo   Look up an item:
echo     costco-lookup.bat --item 1234567
echo.
echo   Inject a token from Chrome DevTools:
echo     costco-lookup.bat --inject-token
echo.
pause
endlocal
